site_name: "CryptoAnalysis Documentation"
site_url: https://crossingtud.github.io/CryptoAnalysis/
repo_url: https://github.com/CROSSINGTUD/CryptoAnalysis/
edit_uri: edit/develop/docs/

nav:
  - Home: index.md
  - Getting Started:
      - Installation and Setup: installation-and-setup.md
      - HeadlessJavaScanner: java-scanner.md
      - HeadlessAndroidScanner: android-scanner.md
      - Error Types: error-types.md
      - Examples: examples.md
      - API: api.md

theme:
  name: material
  logo: ./img/CryptoAnalysisLogo.png
  #  favicon: ./img/icon.png
  palette:
    primary: orange
  features:
    - navigation.sections

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike
