name: CI for Android Cryptographic Misuses

on:
  push:
    branches:
      - android_github_action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Copy Android Platforms to Test Resources
      run: |
        cp -R $ANDROID_SDK_ROOT/platforms/* HeadlessAndroidScanner/src/test/resources/platforms/

    - name: Run Tests
      run: mvn -f HeadlessAndroidScanner clean install 