name: Build And Test (Soot)

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  # Builds the project in ubuntu
  build:
    runs-on: ubuntu-latest
    name: Project build in ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      # Sets up Java version
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: '11'
      # Restores Maven dependecies
      - name: Restore local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run maven command
        run: mvn clean verify -DrunSootTests
