name: Build And Test (Merge Queue)

on:
  merge_group:
    types: [checks_requested]

jobs:
  # Build and test the CryptoAnalysis module
  build-and-test-analysis:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build and Test Analysis in ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      # Sets up Java version
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: '11'
      # Restores Maven dependecies
      - name: Restore local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run maven command
        run: mvn clean verify -DrunAnalysisTests

  # Build and test the HeadlessJavaScanner module with Soot
  build-and-test-scanner:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build and Test JavaScanner (Soot) in ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      # Sets up Java version
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: '11'
      # Restores Maven dependecies
      - name: Restore local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run maven command
        run: mvn clean verify -DrunSootTests