name: Build And Test (Basic)
description: Basic build and tests for the submodules on each pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  # Build the CryptoAnalysis module and run its tests
  build-and-test-analysis:
    strategy:
      fail-fast: false
      matrix:
        framework: [Soot, SootUp, Opal]

    name: Build and test CryptoAnalysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build and test Analysis
        uses: ./.github/actions/analysis
        with:
          java-version: ${{ env.JAVA_VERSION }}
          framework: ${{ matrix.framework }}

  # Build the HeadlessAndroidScanner module and run its tests
  build-and-test-android-scanner:
    name: Build and test HeadlessAndroidScanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build and test HeadlessAndroidScanner
        uses: ./.github/actions/scanner-android
        with:
          java-version: ${{ env.JAVA_VERSION }}

  # Build the HeadlessJavaScanner module and run its tests
  build-and-test-java-scanner:
    strategy:
      fail-fast: false
      matrix:
        framework: [Soot, SootUp, Opal]

    name: Build and test HeadlessJavaScanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build and test HeadlessJavaScanner
        uses: ./.github/actions/scanner-soot
        with:
          java-version: ${{ env.JAVA_VERSION }}
          framework: ${{ matrix.framework }}
