name: Documentation Deployment
description: Deploy the documentation to GitHub pages when modified

on:
  push:
    branches:
      - develop
    create:
      tags:
        - '*'

concurrency:
  group: gh-pages

jobs:
  # On push/merge to develop: Deploy the current doc as default/latest
  deploy-doc-snapshots:
    name: Deploy Snapshot Documentation
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Maven Version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Deploy Snapshot Documentation
        uses: secure-software-engineering/actions/documentation/handle-deployment@fix/documentation-deployment
        with:
          name: ${{ steps.version.outputs.version }}
          title: ${{ steps.version.outputs.version }}

  # On tag creation (i.e. new release): Deploy a stable version to directory with tag
  deploy-doc-stable:
    name: Deploy Stable Documentation
    if: ${{ github.event_name == 'create' && github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Deploy Stable Documentation
        uses: secure-software-engineering/actions/documentation/handle-deployment@fix/documentation-deployment
        with:
          name: ${{ github.ref_name }}
          title: ${{ github.ref_name }}
          stable: true
