name: Aggregate Results
on:
  push:
    branches:
      - test_gh_pages # Or whichever branch you're working on

jobs:
  build-test-aggregate-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code and history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'  

    - name: Build and run tests
      run: mvn clean install

    - name: Create gh-pages-output directory
      run: mkdir -p gh-pages-output

    - name: Aggregate test results
      run: |
        total_time=$(grep -h "Time elapsed" CryptoAnalysis/shippable/testresults/*.txt | awk '{sum += $3} END {print sum}')
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        echo "${timestamp}, Total Time: ${total_time} seconds" >> gh-pages-output/history.txt

    - name: Generate HTML report
      run: |
        echo "<html><body><h1>Aggregated Test Results</h1><ul>" > gh-pages-output/index.html
        cat gh-pages-output/history.txt | while read line; do
          echo "<li>${line}</li>" >> gh-pages-output/index.html
        done
        echo "</ul></body></html>" >> gh-pages-output/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages-output
        keep_files: true  # Keep existing files in the gh-pages branch
