name: Combined CI for Parent and Submodules

on: [push, pull_request]

jobs:
  # Build and test modules with a matrix strategy for OS and module paths
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        module:
          - name: "parent-module"
            path: ". -N"
          - name: "CryptoAnalysis"
            path: "CryptoAnalysis"
          - name: "HeadlessJavaScanner"
            path: "HeadlessJavaScanner"
    runs-on: ${{ matrix.os }}
    name: Build and test ${{ matrix.module.name }} on ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.3

      - name: Restore Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test ${{ matrix.module.name }}
        run: mvn -f ${{ matrix.module.path }} clean install


       # HeadlessAndroidScanner module build and test
  android-module:
    runs-on: ubuntu-latest
    needs: build-and-test 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: List Android platforms
        run: |
          ls -lhR $ANDROID_SDK_ROOT/platforms/

      - name: Copy Android platforms to test resources
        run: |
          cp -R $ANDROID_SDK_ROOT/platforms/* HeadlessAndroidScanner/src/test/resources/platforms/

      - name: Build Android module (skip tests)
        run: mvn clean install -DskipTests

      - name: Test Android module
        run: mvn -f HeadlessAndroidScanner test
