name: Build And Test (Windows)

on:
  merge_group:

env:
  JAVA_VERSION: 17

jobs:
  # This name must be equal to the corresponding build_and_test job
  build-and-test-analysis:
    strategy:
      fail-fast: false
      matrix:
        framework: [Soot, SootUp, Opal]

    name: Build and test CryptoAnalysis
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build and test Analysis
        uses: ./.github/actions/analysis
        with:
          java-version: ${{ env.JAVA_VERSION }}
          framework: ${{ matrix.framework }}

  # This name must be equal to the corresponding build_and_test job
  build-and-test-android-scanner:
    name: Build and test HeadlessAndroidScanner
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build and test HeadlessAndroidScanner
        uses: ./.github/actions/android-scanner
        with:
          java-version: ${{ env.JAVA_VERSION }}

  # This name must be equal to the corresponding build_and_test job
  build-and-test-java-scanner:
    strategy:
      fail-fast: false
      matrix:
        framework: [Soot, SootUp, Opal]

    name: Build and test HeadlessJavaScanner
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build and test HeadlessJavaScanner
        uses: ./.github/actions/java-scanner
        with:
          java-version: ${{ env.JAVA_VERSION }}
          framework: ${{ matrix.framework }}
