name: Build And Test (Windows)

on:
  merge_group:

env:
  JAVA_VERSION: 11

jobs:
  # This name must be equal to the corresponding build_and_test job
  build-and-test-analysis:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      # Sets up Java version
      - name: Set up Java ${{ $env:JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ $env:JAVA_VERSION }}
      # Restores Maven dependecies
      - name: Restore local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run maven command
        run: mvn clean verify -DrunAnalysisTests

  # This name must be equal to the corresponding build_and_test job
  build-and-test-scanner-soot:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      # Sets up Java version
      - name: Set up Java ${{ $env:JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ $env:JAVA_VERSION }}
      # Restores Maven dependecies
      - name: Restore local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run maven command
        run: mvn clean verify -DrunSootTests
