name: Performance Analysis

on:
  push:
  workflow_dispatch:
    #inputs:
    #  analysis:
    #    type: boolean
    #    required: false
    #    default: false
    #  android:
    #    type: boolean
    #    required: false
    #    default: false
    #  soot:
    #    type: boolean
    #    required: false
    #    default: false

env:
  JAVA_VERSION: 17

jobs:
  performance-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and test Analysis
        uses: ./.github/actions/analysis
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Create or update gh-pages-output directory
        run: mkdir -p gh-pages-output

      - name: Extract performance
        uses: ./.github/actions/performance
        with:
          test-results-path: CryptoAnalysis/shippable/testresults
          source-branch: gh-pages
          current-results: analysis_history.txt
          output-file: gh-pages-output/analysis_history.txt

      - name: Store Analysis performance
        uses: actions/upload-artifact@v4
        with:
          name: analysis-performance
          path: gh-pages-output/analysis_history.txt

  performance-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Build and test Android Scanner
        uses: ./.github/actions/scanner-android
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Create or update gh-pages-output directory
        run: mkdir -p gh-pages-output
      
      - name: Extract performance
        uses: ./.github/actions/performance
        with:
          test-results-path: HeadlessAndroidScanner/shippable/testresults
          source-branch: gh-pages
          current-results: android_history.txt
          output-file: gh-pages-output/android_history.txt
          
      - name: Store Android performance
        uses: actions/upload-artifact@v4
        with:
          name: android-performance
          path: gh-pages-output/android_history.txt

  performance-soot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and test JavaScanner with Soot
        uses: ./.github/actions/scanner-soot
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Create or update gh-pages-output directory
        run: mkdir -p gh-pages-output
      
      - name: Extract performance
        uses: ./.github/actions/performance
        with:
          test-results-path: HeadlessJavaScanner/shippable/testresults
          source-branch: gh-pages
          current-results: soot_history.txt
          output-file: gh-pages-output/soot_history.txt
          
      - name: Store Soot performance
        uses: actions/upload-artifact@v4
        with:
          name: soot-performance
          path: gh-pages-output/soot_history.txt

  performance-report:
    runs-on: ubuntu-latest
    needs: [performance-analysis, performance-android, performance-soot]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Load performance files
        uses: actions/download-artifact@v4
        with:
          path: gh-pages-output
          merge-multiple: true

      - name: Generate HTML report
        run: |
          echo "<html><body>" > gh-pages-output/index.html
          echo "<div style=\"display: flex; flex-wrap: wrap; gap: 0 50px;\">" >> gh-pages-output/index.html

          echo "<div style=\"flex: 1 1 200px; min-width: 200px;\"><h1>Analysis</h1><ul>" >> gh-pages-output/index.html

          if [ -f gh-pages-output/analysis_history.txt ]; then
            cat gh-pages-output/analysis_history.txt | while read line; do
              echo "${line}"
              echo "<li>${line}</li>" >> gh-pages-output/index.html
            done
          fi

          echo "</ul></div>" >> gh-pages-output/index.html

          echo "<div style=\"flex: 1 1 200px; min-width: 200px;\"><h1>AndroidScanner</h1><ul>" >> gh-pages-output/index.html

          if [ -f gh-pages-output/android_history.txt ]; then
            cat gh-pages-output/android_history.txt | while read line; do
              echo "${line}"
              echo "<li>${line}</li>" >> gh-pages-output/index.html
            done
          fi

          echo "</ul></div>" >> gh-pages-output/index.html

          echo "<div style=\"flex: 1 1 200px; min-width: 200px;\"><h1>JavaScanner (Soot)</h1><ul>" >> gh-pages-output/index.html

          if [ -f gh-pages-output/soot_history.txt ]; then
            cat gh-pages-output/soot_history.txt | while read line; do
              echo "${line}"
              echo "<li>${line}</li>" >> gh-pages-output/index.html
            done
          fi

          echo "</ul></div>" >> gh-pages-output/index.html

          echo "</div>" >> gh-pages-output/index.html
          echo "</body></html>" >> gh-pages-output/index.html
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-output

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          failOnError: false
          name: |
            analysis-performance
            android-performance
            soot-performance
