name: Test Internal Action

on: push

jobs:
  internal_action:
    runs-on: ubuntu-latest
    name: Test CryptoAnalysis Action
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run CogniCrypt
        uses: ./
        with:
          appPath: "$(pwd)/CryptoAnalysisTargets/CogniCryptDemoExample/Examples.jar"
          basePath: "CryptoAnalysisTargets/CogniCryptDemoExample/src/main/java"
