name: Test Internal Action

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  internal_action:
    runs-on: ubuntu-latest
    name: Test CryptoAnalysis Action
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run CogniCrypt
        uses: ./
        with:
          appPath: "CryptoAnalysisTargets/HelloWorld/HelloWorld.jar"
          basePath: "CryptoAnalysisTargets/HelloWorld"
