name: Test Internal Action

on: push

jobs:
  internal_action:
    runs-on: ubuntu-latest
    name: Test CryptoAnalysis Action
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run CogniCrypt
        uses: Timbals/CryptoAnalysis@be1b88d536592c3ab08af5969808d075b8c59d82
        with:
          rulesDir: "$(pwd)/JCA-CrySL-rules"
          appPath: "$(pwd)/CryptoAnalysisTargets/CogniCryptDemoExample/Examples.jar"
          basePath: "CryptoAnalysisTargets/CogniCryptDemoExample/src/main/java"
