name: Test Internal Action

on: push

jobs:
  internal_action:
    runs-on: ubuntu-latest
    name: Test CryptoAnalysis Action
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run CogniCrypt
        uses: Timbals/CryptoAnalysis@a4032930f0a7b3bdb761130eae8d2229c9534b0a
        with:
          rulesDir: "$(pwd)/JCA-CrySL-rules"
          appPath: "$(pwd)/CryptoAnalysisTargets/CogniCryptDemoExample/Examples.jar"
          basePath: "CryptoAnalysisTargets/CogniCryptDemoExample/src/main/java"
